# Site settings
title: 我也在世界末尾
header-img: "img/green.jpg"
tagline: "cn"  
description: "好巧，你也来到世界末尾了。"  
baseurl: ""
url: ""  

# About/contact
owner: 
  name: " WingjeySong"
  email: winjey-song@163.com
  bio: "不破不立，不成不休。"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/handwriting_W.png

douban_username:  
twitter_username: 
github_username: 
facebook_username: 
weibo_username: 
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Hangzhou

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "WingjeySong"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
